
import "./globals.css";
import Navbar from "@/app/components/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,modal }) {
  return (
    <html lang="en">
      <body>

      <Navbar></Navbar>
        {children}
        {modal}
      </body>
    </html>
  );
}
